### ISSUE TITLE
Won't download the music if no cover image found

### ISSUE THREAD

**Issue by taducquang** [ebb-earl-co/tidal-wave#137]
When i tried to download a song, it refused to download cause no album cover is found: 
tidal-wave https://tidal.com/browse/album/118613014 --audio-format hires --loglevel warning --no-extra-files

Output log:
```
2024-04-07:00:03:00,724 WARNING  [album.py:182] No cover image was returned from TIDAL API for album 118613014
Traceback (most recent call last):

  File "<frozen runpy>", line 198, in _run_module_as_main

  File "<frozen runpy>", line 88, in _run_code

  File "C:\Python312\Scripts\tidal-wave.exe\__main__.py", line 7, in <module>
    sys.exit(app())
             ^^^^^

  File "C:\Python312\Lib\site-packages\tidal_wave\main.py", line 108, in main
    album.get(

  File "C:\Python312\Lib\site-packages\tidal_wave\album.py", line 191, in get
    self.cover_path.unlink()
    ^^^^^^^^^^^^^^^

AttributeError: 'Album' object has no attribute 'cover_path'
```

Hope someone fix this.

**Comment by ebb-earl-co** [comment]
@taducquang thank you for having raised this issue. It is indeed a bug, and I will work on a fix to be included in the next release!

**Comment by ebb-earl-co** [comment]
@taducquang this should be included in the newest changes in the `trunk` branch. I.e., if you use Docker, pull the latest image, and it will be fixed in there.

Otherwise, you'll have to wait a little bit for me to get version 2024.4.1 released. But it will be included in that version.
