### ISSUE TITLE
I get error

### ISSUE THREAD

**Issue by pablo-reyes-cabrera** [ebb-earl-co/tidal-wave#53]
Hi, 

Thanks for your app. I get an error when I try to use it.

Pablo

xx@MacBook-Pro ~ % tidal-wave --audio-format 'HiRes'  https://tidal.com/browse/playlist/70bcff2a-ec53-4956-b349-267d9a0cf116 
2024-01-18:14:45:14,965 INFO     [models.py:621] TIDAL playlist ID parsed from input: 70bcff2a-ec53-4956-b349-267d9a0cf116
For which of Android [a] or Windows [w] would you like to provide an API token?: w
2024-01-18:14:45:17,876 INFO     [requesting.py:89] Requesting from TIDAL API: playlists/70bcff2a-ec53-4956-b349-267d9a0cf116
2024-01-18:14:45:18,132 INFO     [playlist.py:351] Requesting from TIDAL API: playlists/70bcff2a-ec53-4956-b349-267d9a0cf116/items
2024-01-18:14:45:18,398 INFO     [requesting.py:89] Requesting from TIDAL API: albums/3489559
2024-01-18:14:45:18,465 INFO     [requesting.py:89] Requesting from TIDAL API: tracks/10827167/credits
2024-01-18:14:45:18,531 INFO     [requesting.py:89] Requesting from TIDAL API: tracks/10827167/playbackinfopostpaywall
Traceback (most recent call last):

  File "/opt/homebrew/bin/tidal-wave", line 8, in <module>
    sys.exit(app())
             ^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/tidal_wave/main.py", line 116, in main
    playlist.get(

  File "/opt/homebrew/lib/python3.11/site-packages/tidal_wave/playlist.py", line 317, in get
    _get_items = self.get_items(session, audio_format)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/tidal_wave/playlist.py", line 105, in get_items
    track.get(

  File "/opt/homebrew/lib/python3.11/site-packages/tidal_wave/track.py", line 519, in get
    self.set_manifest()

  File "/opt/homebrew/lib/python3.11/site-packages/tidal_wave/track.py", line 87, in set_manifest
    self.manifest: Manifest = manifester(self.stream)
                              ^^^^^^^^^^^^^^^^^^^^^^^

  File "/opt/homebrew/lib/python3.11/site-packages/tidal_wave/dash.py", line 137, in manifester
    raise TidalManifestException(

tidal_wave.dash.TidalManifestException: Manifest for track 10827167, audio mode STEREO is encrypted

**Comment by ebb-earl-co** [comment]
@pablo-reyes-cabrera the last line of the error is the important one: it looks as if the first track in the playlist is unable to be converted because it is encrypted. I see that you've selected a Windows (`w`) token to have the program use: how did you get this token? Are you positive that this token has permission to download tracks?

**Comment by pablo-reyes-cabrera** [comment]
Hi!, I got the token using Charles (in macOS). For the other part, I have the permission to download tracks (on the tidal-dl I can download tracks). maybe the issue is that the tracks are MQA?

thanks in advance, 
Pablo

**Comment by ebb-earl-co** [comment]
@pablo-reyes-cabrera at the moment, the program doesn’t work with credentials from macOS. But, similar to `tidal-dl`, you can get tracks from a spoofed Fire TV if you use `--audio-format mqa` instead of `--audio-format hires`
